services:
  web:
    environment:
      - HTTP_PORT=3000
      - SECONDARY_HTTP_PORT=3001
      - TCP_PORT=4000
    domain: ${HOST}
    internal: true
    build: .
    port: 3000
    ports:
     - 3001
     - 4000
    health:
      grace: 30
      interval: 15
      path: /health
      timeout: 30